### ISSUE TITLE
Send more compact query

### ISSUE THREAD

**Issue by gaku-sei** [Zaid-Ajaj/Snowflaqe#23]
It seems that Snowflaqe currently sends the exact GraphQL queries and mutations as the ones defined in the GraphQL files. So given this query:

```graphql
query Countries {
  name
}
```

This code will be generated in the `GraphqlClient` module:

```f#
member _.Countries() =
  async {
    let query = """
      query Countries {
        name
      }
      """

  // ...
```

Which has 2 drawbacks:
1. The sent payload will be heavier (since it includes line returns and spaces)
2. Some servers' libraries (like Elixir's Absinthe) don't support queries containing line returns (natively)

Is there an option to generate "compact" queries and mutations?

**Comment by Zaid-Ajaj** [comment]
Hi there @gaku-sei, 

Currently there isn't an option to minify the the input query because usually size of the query itself isn't so much of a problem the problem with all the whitespace. 

> Some servers' libraries (like Elixir's Absinthe) don't support queries containing line returns (natively)

This is very interesting, I never thought that such limitation of a server would be a thing because, you know, whitespace is allowed according to the [specs](https://spec.graphql.org/June2018/#sec-Source-Text.Ignored-Tokens). 

In any case, the goal of Snowflaqe to be compatible with as many server-side libraries as possible. So this is definitely a feature to add here. 

Would you like to give the issue a try? That would be awesome :smile:

**Comment by Zaid-Ajaj** [comment]
@gaku-sei Before I look at the technical details of making compact queries, can you please test to see for yourself whether queries in their full form don't already work with Elixir's Absinthe? 

The generic JS client [docs](https://hexdocs.pm/absinthe/javascript.html#over-http) don't mention compact queries and say the server will work with any client (like the one Snowflaqe generates)

**Comment by gaku-sei** [comment]
Hello @Zaid-Ajaj 😄 

Sorry, my first port wasn't clear enough about the issue ^^
So the issue is not that the graphql query contains whitespaces or line returns but that the latter are not escaped in the payload (line returns are not accepted in JSON strings byt most JSON libraries 😕 ). So The idead would be whether to inline the query or to escape the line returns. And while at it, I wondered if it wouldn't be better to just "compact" the query to save some bytes here and there (while I totally agree it would be some very small optimization, and it should be done in production mode only as it impacts the readability 😕 ).

If that sounds good to you I don't mind taking a look at the way the code is generated and try to make a PR next week 😄

**Comment by Zaid-Ajaj** [comment]
> it seems that the Fable.SimpleJson.Json.serialize function doesn't escape the line returns.

Can you please elaborate with an example payload fails when serialized or is serialized incorrectly? `Json.serialize` doesn't even generate line returns or intendentation between in the JSON structure but it does generate valid JSON

**Comment by gaku-sei** [comment]
Sure I will post a full reproduction as soon as possible 👍

**Comment by Zaid-Ajaj** [comment]
You are right @gaku-sei I just did some test and indeed Fable.SimpleJson needs to properly escape the characters, thanks for the example. (Btw, when you update your message, I don't get notifications, so feel free to comment more so that I can answer you quickly :wink:)

**Comment by Zaid-Ajaj** [comment]
Just pushed version v1.12 of Snowflaqe which references version 3.16.2 of SimpleJson that implements proper string escaping. 

Can you please take it for a spin and let me know if the issue is resolved? Thanks! 🙏

**Comment by Zaid-Ajaj** [comment]
Awesome, thanks for the confirmation! If you come across any more issues, please let me know 🙏

**Comment by Zaid-Ajaj** [comment]
Awesome, thanks for the confirmation! Please let me know if you encounter any more issues 🙏

**Comment by gaku-sei** [comment]
That was a very fast fix!! Thank you very much @Zaid-Ajaj it works like a charm now 🎊 

>Btw, when you update your message, I don't get notifications, so feel free to comment more so that I can answer you quickly

Sure, I wasn't aware of this, I will do that next time 😄
