### ISSUE TITLE
Add comment to indicate auto-generated code

### ISSUE THREAD

**Issue by OttoBos** [Zaid-Ajaj/Snowflaqe#28]
Hi, would be good if the auto-generated code would contain some comment header to indicate it was auto-generated by snowflaqe, maybe even including the date / GraphQL URI / name of query file, and a link to the snowflaqe repo of course.
This would avoid people manually editing these files.

**Comment by Zaid-Ajaj** [comment]
Hi @OttoBos, this sounds like a good idea. I'll add it as a configuration option sometime soon 😄

**Comment by Zaid-Ajaj** [comment]
Fixed as of v1.19 🚀 Snowflaqe will now emit code generation metadata when when the option `emitMetadata` is set to `true`
```json
{
    "emitMetadata": true
}
```
This option is set to `false` by default when you do not provide in the configuration.
