### ISSUE TITLE
Merge GraphQL support efforts

### ISSUE THREAD

**Issue by xperiandri** [Zaid-Ajaj/Snowflaqe#30]
Currently we have your amaring client as generator and github.com/FSProjecrs/FSharp.Data.GraphQL as server and type provider.
Maybe it worse to merge efforts and integrate both projects together?

**Comment by Zaid-Ajaj** [comment]
Hi there @xperiandri,

How do you imagine merging the efforts? To me, Snowflaqe is pretty much a standalone project for consuming GraphQL endpoints regardless of a specific backend type (FSharp.Data.GraphQL or otherwise).

Would be happy to accept PRs / contributions to Snowflaqe directly :wink:

**Comment by xperiandri** [comment]
I suppose that your code can be reused in GraphQL client type provider

**Comment by Zaid-Ajaj** [comment]
That won't work. The code used here generates records and union types which type providers ironically don't support. Not to mention making the type provider compatible with Fable is a huge pain in the back, compared to the situation now where things just work out of the box
