### ISSUE TITLE
Implement async handling option: "async" | "task" for the fsharp target

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Zaid-Ajaj/Snowflaqe#31]
Basically:
```
{
   ["asyncReturnType"]: < "async" | "task" >
}
```
Where `async` is the default. To make the generated functions either return `Async<'T>`  or `Task<'T>` 

For the latter you would need to include `Ply` as a dependency to the generated F# project. 

Related to #29 

Might need a better API for generating the projects and their packages.

**Comment by Numpsy** [comment]
Is https://github.com/Numpsy/Snowflaqe/commit/d4f91f78efe5b526d2961fc6d5243cd71fa8d3ed the right sort of thing?

Notes:

- I'm largely making it up as I go along, and am not certain what stringBuffer is giving you in some cases.
- Is Async.AwaitTask/Async.RunSynchronously the approach you'd want with tasks? (When I've done the sync-over-async thing with tasks in C# it was using the GetAwaiter().GetResult() type approaches, not sure what the best approach is in F#).

**Comment by Zaid-Ajaj** [comment]
@Numpsy you are on the right track, here is a checklist from the top of my head:
 - don't worry about stringBuffer, it just concatenates the strings
 - when checking `if isNull parsedJson.["asyncReturnType"] || string parsedJson.["asyncReturnType"] = "async"`, the expression `string parsedJson.["asyncReturnType"]` should be lower-cased (same when validating)
 - should return a parse error if `asyncReturnType = task && target = fable` because Fable doesn't support tasks
 - should include nuget `Ply @ v0.3.1` when `asyncReturnType = task` 
 - should open namespace `FSharp.Control.Tasks` when `asyncReturnType = task` 
 - Using `GetAwaiter().GetResult()` for sync sounds good. It doesn't matter that much, both should work fine

**Comment by Numpsy** [comment]
>     * don't worry about stringBuffer, it just concatenates the strings

I'd thought it did, but then it looked like some of the existing uses only contain a single string, so I wasn't sure if I was missing something :-(

>     * when checking `if isNull parsedJson.["asyncReturnType"] || string parsedJson.["asyncReturnType"] = "async"`, the expression `string parsedJson.["asyncReturnType"]` should be lower-cased (same when validating)

Hmm, I copied that from the existing code @ https://github.com/Zaid-Ajaj/Snowflaqe/blob/c02fd6ef4010ab2ad7773ea2db5aa28ba6558596/src/Program.fs#L106 and had missed that it lower cases the string when validating and not when using it (so it seems that setting ```target``` to ```Fable``` (capital F) with the current release actually causes it to generate a ```Shared``` Project (is that considered a bug then?)

>     * Using `GetAwaiter().GetResult()` for sync sounds good. It doesn't matter that much, both should work fine (if it is easier to leave it as is, I am fine with that)

Doing ```GetAwaiter().GetResult()``` directly on the task returned from the Async function should be straight forward, but I had a go at calling it through ```Task.Run``` instead and got some overload resolution errors, so sticking to the F# functions which just worked was easier (too many ways of doing the same thing!)

**Comment by Zaid-Ajaj** [comment]
> and had missed that it lower cases the string when validating and not when using it (so it seems that setting target to Fable (capital F) with the current release actually causes it to generate a Shared Project (is that considered a bug then?)

Yes, that's a bug!

**Comment by Numpsy** [comment]
Considered resolved by merging #47 ?

I'd wondered about adding CancellationToken parameters to the Task returning variants of the functions, but that could be a seperate change if needed.

**Comment by Zaid-Ajaj** [comment]
This is resolved and tested locally! thanks a lot @Numpsy ❤️ you can try this out as of v1.26

**Comment by Zaid-Ajaj** [comment]
Let's worry about the cancellation token in a different issue 😉
