### ISSUE TITLE
Generate props file with referenced fs files

### ISSUE THREAD

**Issue by xperiandri** [Zaid-Ajaj/Snowflaqe#34]
It would be nice to have a props file generated. This will allow scenario:

client.fsproj: `<Import Project="output/generated.props" />`

/output
    \<generated F# files\>
    \<project name\>.props
``` XML
    <ItemGroup>
        <Compile Include="Query1.fs" />
        ...
    </ItemGroup>
```

**Comment by Zaid-Ajaj** [comment]
That looks like a doable improvement. Preferably via an option `["generateProps"]: <true | false>` where `false` is default. 

I am not sure how the `props` file will look like though, can you provide a full example?

**Comment by xperiandri** [comment]
The file extension can be any. Content matters.
It will be something like:
``` XML
<ItemGroup>
    <Compile Include="Types.fs" />
    <Compile Include="Query1.fs" />
    <Compile Include="Query2.fs" />
    ...
    <Compile Include="QueryN.fs" />
    <Compile Include="Client.fs" />
</ItemGroup>
```

That is all.

The main point is to include files in the right order and do not do that manually.

**Comment by xperiandri** [comment]
Just a piece of `fsproj` extracted to separate file and auto-generated

**Comment by anthony-mi** [comment]
I want to realize this opportunity. How to name the key that will switch generation between fsproj and props?

**Comment by anthony-mi** [comment]
I would like to use StringBuffer
```
type StringBuffer = StringBuilder -> unit

type StringBufferBuilder () =
    member inline __.Yield (txt: string) = fun (b: StringBuilder) -> Printf.bprintf b "%s" txt
    member inline __.Yield (c: char) = fun (b: StringBuilder) -> Printf.bprintf b "%c" c
    member inline __.Yield (b: byte) = fun (sb: StringBuilder) -> Printf.bprintf sb "%02x " b
    member inline __.YieldFrom (strings: #seq<string>) =
        fun (b: StringBuilder) ->
            for s in strings do Printf.bprintf b "%s" s

    member inline __.YieldFrom (f: StringBuffer) = f
    member __.Combine (f, g) = fun (b: StringBuilder) -> f b; g b
    member __.Delay f = fun (b: StringBuilder) -> (f()) b
    member __.Zero () = ignore

    member __.For (xs: 'a seq, f: 'a -> StringBuffer) =
        fun (b: StringBuilder) ->
            use e = xs.GetEnumerator ()
            while e.MoveNext() do
                (f e.Current) b

    member __.While (p: unit -> bool, f: StringBuffer) =
        fun (b: StringBuilder) -> while p () do f b

    member __.Run (f: StringBuffer) =
        let b = StringBuilder()
        do f b
        b.ToString()

let stringBuffer = new StringBufferBuilder ()
```
Can I add it to the project?

**Comment by anthony-mi** [comment]
I would like to generate fsproj using XDocument, XElement. Can I rewrite the generation on them?

**Comment by Zaid-Ajaj** [comment]
Hi @anthony-mi maybe I didn't understand the issue correctly, does this _replace_ the fsproj entirely? if so, what about the external dependencies that the project uses, specifically `Fable.Remoting.Client`?

**Comment by Zaid-Ajaj** [comment]
> I would like to generate fsproj using XDocument, XElement. Can I rewrite the generation on them?

That would be a nice improvement to the current API (which uses strings) to build the project file but that is a separate issue

**Comment by xperiandri** [comment]
It depends on your intent. If you want to go away from `fsproj` to props as I propose than we do that

**Comment by xperiandri** [comment]
But if you wan to keep the ability to have full project, then we need to introduce a switch

**Comment by xperiandri** [comment]
What is your opinion?

**Comment by Zaid-Ajaj** [comment]
There is already a switch called `target` which takes `<fable | fsharp | shared>` to which we can add `propsFile` or just `props` as another type of target but the question remains, what do you do with the external dependencies that are added and used in `GraphqlClient.fs`?

**Comment by xperiandri** [comment]
They can be added to props also

**Comment by xperiandri** [comment]
But it is better to add them manually

**Comment by xperiandri** [comment]
To the project file

**Comment by xperiandri** [comment]
> There is already a switch called target which takes <fable | fsharp | shared> to which we can add propsFile
But `props` can be generated for any target

**Comment by Zaid-Ajaj** [comment]
> They can be added to props also

So it is not just the files 
```xml
<ItemGroup>
    <Compile Include="Types.fs" />
    <Compile Include="Query1.fs" />
    <Compile Include="Query2.fs" />
    ...
    <Compile Include="QueryN.fs" />
    <Compile Include="Client.fs" />
</ItemGroup>
```
but also with package references added
```xml
<ItemGroup>
    <Compile Include="Types.fs" />
    <Compile Include="Query1.fs" />
    <Compile Include="Query2.fs" />
    ...
    <Compile Include="QueryN.fs" />
    <Compile Include="Client.fs" />
</ItemGroup>
<ItemGroup>
    <PackageReference Update="FSharp.Core" Version="4.7.2" />
    <PackageReference Include="Fable.Remoting.Json" Version="2.14.0" />
</ItemGroup>
```
is that correct?

**Comment by xperiandri** [comment]
Yes we can do that. But I think that this 2 dependencies any developer can ad himself into his project as well as `<Import Project="GraphQLClient.props" />`

**Comment by Zaid-Ajaj** [comment]
I would rather have snowflaqe decide which dependencies are used because they are tied to the code generation. If a I fix something in the serializer and update snowflaqe to a new version, they would get the new version with the proper dependency versions etc.

**Comment by xperiandri** [comment]
That's fine, developer can override it in consumption project any way

**Comment by xperiandri** [comment]
Do you approve `stringBuffer` and `XDocument`?

**Comment by Zaid-Ajaj** [comment]
`stringBuffer` I don't mind, `XDocument` yes please! 🙏

**Comment by anthony-mi** [comment]
Changed fsproj generation to props - everything works.
![Screenshot_124](https://user-images.githubusercontent.com/65635298/114762961-f7895980-9d6a-11eb-86de-22d42eb88aa5.png)
![Screenshot_129](https://user-images.githubusercontent.com/65635298/114762966-f8ba8680-9d6a-11eb-8bac-9b1d23c3d7e1.png)

**Comment by Zaid-Ajaj** [comment]
Added option `createProjectFile` to implement this feature thanks to @anthony-mi where the value `false` makes snowflaqe output a props file instead of a project (see docs in readme)
