### ISSUE TITLE
Complex object for errorType?

### ISSUE THREAD

**Issue by bdaniel7** [Zaid-Ajaj/Snowflaqe#55]
Is there a way to configure the errorType to be a more complex object?
Like an array/list of error objects.
```
"errors": [
    {
      "message": "Invalid cursor provided for the after parameter: a",
      "locations": [{ "line": 2, "column": 3 }],
      "path": ["vessels"],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
```

**Comment by Zaid-Ajaj** [comment]
Yes! See [the docs here](https://github.com/Zaid-Ajaj/Snowflaqe#custom-error-type)

**Comment by Zaid-Ajaj** [comment]
In your case, it would be
```json
"errorType": {
        "CustomErrorType": {
            "message": "string"
            "path": "string list"
            "extensions": "dictionary<string, string>"
        }
}
```
As for `locations`, there isn't a generic way to describe such type (list of other complex objects) but it should be doable to add if you _REALLY_ need it

**Comment by Zaid-Ajaj** [comment]
I believe this is resolved as well? I'll close the issue, please re-open if the problem persists

**Comment by Zaid-Ajaj** [comment]
@bdaniel7 Didn't the proposed solution work for you?

**Comment by bdaniel7** [comment]
Hmm, I see now that it does fill the error object:
```
{ message =
   "Cannot query field "updateTimestamps" on type "Vessel". Did you mean "updateTimestamp"?"
  path = null
  extensions = seq [[code, GRAPHQL_VALIDATION_FAILED]] }
```
Ok, I will use the custom error object as you recommended, thank you.
