### ISSUE TITLE
Readme instructions don't work

### ISSUE THREAD

**Issue by MargaretKrutikova** [Zaid-Ajaj/Snowflaqe#6]
The first thing to do according to the instructions is `dotnet install snowflaqe -g`, which fails.
The correct one is `dotnet tool install snowflaqe -g`, found it [here](https://fable.io/blog/Introducing-Snowflaqe.html).

Any chance the readme could be corrected?

**Comment by Zaid-Ajaj** [comment]
Hi @MargaretKrutikova, thanks a lot for pointing the silly mistake, really appreciate it 🙏 It is now fixed and the README shows the correct install command
