### ISSUE TITLE
Tags is not a valid name for a DU case

### ISSUE THREAD

**Issue by l3m** [Zaid-Ajaj/Snowflaqe#61]
The F# compiler does not allow a union case called Tags as it's a member used internally. Aa related issue with some discussion can be found [here](https://github.com/fsharp/fslang-design/blob/main/RFCs/FS-1079-union-properties-visible.md)

Snowflaqe generates a Tags DU member if the GraphQL endpoint has a corresponding name (I stumbled upon it for the monday.com api).

This will cause Snowflaqe to generate a project that cannot be compiled. 

A work around is to rename the generated member, but this has to be done after every project regeneration.

**Comment by Zaid-Ajaj** [comment]
Hi @l3m, thanks for filing the issue. Fixed as of Snowflaqe v1.33 :rocket: Now generated case name is `TAGS` but the compiled name stays `Tags` so the runtime will keep working. I guess this is a rare edge case so `TAGS` isn't too bad to work with, I hope 🙏
