### ISSUE TITLE
How to use the generated code?

### ISSUE THREAD

**Issue by MargaretKrutikova** [Zaid-Ajaj/Snowflaqe#7]
The readme shows how to generate the code, but not how to actually send the graphql queries and use the generated types. Also, do I have to manually include the generated code in the project file?
Really appreciate some instructions on this!

The tool works flawlessly otherwise 🙂

**Comment by Zaid-Ajaj** [comment]
Hi @MargaretKrutikova, let me walk you through this. Suppose you have the following config:
```json
{ 
  "schema": "https://metaphysics-production.artsy.net",
  "project": "Artsy", 
  "output": "./generated", 
  "queries": "./queries", 
  "target": "fable" 
}
```
> This is assuming you are targeting Fable which means you want to use the project from Fable. In case you want to use the project with dotnet/F# then the "target" property should be "fsharp" instead of Fable .

Then when you run `snowflaqe --generate`, it will create a full *F# Project* within the `./generated` directory with of the name `Artsy`. You should be able to see a project file at the path `./generated/Artsy.fsproj`. This project includes types for queries and also a *client* type with methods for each query that were provided in the `./queries` directory. 

Once the queries are validated and the project is generated, you can *reference* that project within *your* Fable project by adding a project reference to it as follows:
```xml
  <ItemGroup>
    <ProjectReference Include="..\generated\Artsy.csproj" />
  </ItemGroup>
```
> if you don't want to add the reference by hand into your project file, use [dotnet add reference](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-add-reference) command instead. 

Assuming your project is located like this:
```
|
| -- src
       | -- YourProject.fsproj
| -- generated
      | -- Artsy.fsproj
```
So now the project `./src/YourProject.fsproj` is referencing `./generated/Artsy.fsproj` and you can start using the client. It goes like this:
```fs
module YourModule

open Artsy // or open whatever name you gave in the {project} config

let client = ArtsyGraphqlClient("https://metaphysics-production.artsy.net)

async {
  let! response = client.QueryName { VariableName = someValue }
  // do stuff with the response 
}
```
I hope this helps, if you have more questions, just me know :smile:

**Comment by MargaretKrutikova** [comment]
Hi @Zaid-Ajaj !

Thanks a lot for the explanation, I made my first mutation to work now 😀  I got confused when I saw a lot of generated files but missed the project file itself, so I thought I had to manually include them in my main project 🤦‍♀️

Anyway, everything is working very smoothly with `Snowflaqe`, if you have time, it would be very helpful to include an actual sample project in the repository, could really assist beginners, like me. An alternative would be to just include your response in the readme 🙂   

Thanks a lot for your hard work on the library!
