### ISSUE TITLE
Problems when using generated input types from Hasura backend

### ISSUE THREAD

**Issue by gmlion** [Zaid-Ajaj/Snowflaqe#76]
I'm facing several issues trying to execute mutation on a F# backend towards Hasura, sending instances of the generated input types, such as
```
type Example_insert_input =
    { AnotherType: Option<AnotherType_obj_rel_insert_input>
      anotherType: Option<string>
      id: Option<string>
    }
```

When using default serializer Newtonsoft.Json, it throws an exception `A member with the name 'anotherType' already exists on 'KrevS2Graphql.SkillModelVersion_insert_input'. Use the JsonPropertyAttribute to specify another name.`

When using System.Text.Json ("system") serializer, Hasura return an error due to a mismatch between discriminated union names. Upon further investigation, this is caused by the fact that the `CompiledName` attributed is not respected.
Next step is to set "normalizeEnumCases" to false.
This solves the previous issues, but another error is given back by Hasura: `expected an object for type 'Example_bool_exp', but found null`. So, it looks like properties set to `None` on the various types generated by Snowflaqe are not serialized in a way that Hasura correctly receive them - I think those properties should be excluded, instead of defined with a `null` value.

**Comment by gmlion** [comment]
I think I found the root problem for the last stopper
https://github.com/Tarmil/FSharp.SystemTextJson/issues/140

**Comment by Zaid-Ajaj** [comment]
Hi there @gmlion thanks for filing the issue! I am able to reproduce it locally with a console app as follows:
```fs
open Newtonsoft.Json
open Fable.Remoting.Json

type Example_insert_input =
    { AnotherType: Option<int>
      anotherType: Option<string>
      id: Option<string>
    }

let fableJsonConverter = FableJsonConverter() :> JsonConverter

let input = {
    AnotherType = Some 1
    anotherType = Some "test"
    id = Some "test"
}

let settings = JsonSerializerSettings(DateParseHandling=DateParseHandling.None, Converters = [| fableJsonConverter |])
let inputJson = JsonConvert.SerializeObject(input, settings)

printfn $"{inputJson}"
```
This is an issue in Fable.Remoting.Json, the specialized JSON serializer used in generated clients. It looks like we don't handle records in any special way and default to whatever Newtonsoft.Json does. Being unable to serialize this trivial type is not ideal. I'll have a look at it 😄

**Comment by Zaid-Ajaj** [comment]
Fixed as of Snowflaqe v1.41 🚀 which should work using the default (newtonsoft) serializer. Please take it for a spin and let me know how it goes 😁

**Comment by gmlion** [comment]
Hey, thanks for the fix.
The first issue with Newtonsoft is indeed fixed with the last update, but now I still have problem #3, which it turns out does not depend on the specific serializer used.

All the properties set to `None` are serialized as null values, so using the generated types with Hasura does not work.
This includes both the properties of the graphql types which should be optional and the other properties of the DTO, such as on_conflict, constraint, update_columns, where.

An example error from Hasura is `expected an object for type 'ExampleType_bool_exp', but found null`

**Comment by Zaid-Ajaj** [comment]
@gmlion In GraphQL, as far as I know, setting `null` for optional fields is fine and accepted. So I am not sure why hasura is not happy with nulls. However, I am think we can fix it on our side of things. It could be another option in JsonSerializerSettings. I will have a look

**Comment by Zaid-Ajaj** [comment]
> but now I still have problem number 3, which it turns out does not depend on the specific serializer used.

@gmlion Should be resolved as of Snowflaqe v1.42 🚀 please give it a try and let me know how it goes 😄

**Comment by gmlion** [comment]
Hi, the situation is partially fixed. Now properties of the original type are no longer serialized as null, but others still are (`on_conflict`, `where`)

**Comment by Zaid-Ajaj** [comment]
@gmlion did you version 1.42 or v1.43? because latest v1.43 should solve this problem entirely.

**Comment by gmlion** [comment]
It is now working, thank you very much!
