### ISSUE TITLE
Escape reserved keywords with backticks

### ISSUE THREAD

**Issue by etareduction** [Zaid-Ajaj/Snowflaqe#85]
Usage of reserved keywords like `constraint` as identifier produces compiler warnings, they should be somehow escaped too.

**Comment by Zaid-Ajaj** [comment]
Can you please provide an example schema and query for me to debug? 🙏

**Comment by etareduction** [comment]
@Zaid-Ajaj
> Can you please provide an example schema and query for me to debug? 🙏

Implemented it in #86, you might add some other tests if necessary.
