### ISSUE TITLE
Meta: Maintenance plans

### ISSUE THREAD

**Issue by john-rodewald** [Zaid-Ajaj/Snowflaqe#95]
Hi @Zaid-Ajaj! 👋 

First off, thanks a lot for authoring Snowflaqe. Without it, I probably never would have gone down the GraphQL route in our .NET project some days ago. I spent a few hours setting things up and it seems to work quite nicely!

I am playing with the idea of using Hasura + Snowflaqe in a new, small-scale F# project at our company. Before I commit to this, it would be nice to hear what your plans are in terms of maintaining Snowflaqe. Will you continue to put time into it in the future or do you think other things are taking priority for you these days? Are you keeping an eye on issues here? 

Thanks again!

**Comment by Zaid-Ajaj** [comment]
Hi @john-rodewald, thanks a lot for the kind words 🙏 I am glad you got Snowflaqe working! 

> Will you continue to put time into it in the future or do you think other things are taking priority for you these days? Are you keeping an eye on issues here?

I do keep an eye on issues and try to resolve issues when I can. I enjoy working on Snowflaqe when times permits. Currently there are no planned work in terms of features (for example subscription support) but will try to resolve issues, review PRs and publish packages. That said, these days I am mostly busy with my day job so if I am unavailable for a while, it won't be unexpected.
